load("@rules_java//java:defs.bzl", "java_binary")

java_binary(
    name = "SendActual",
    srcs = ["SendActual.java"],
    deps = [
        "//java/api-client:java_api_lib",
    ],
)

java_binary(
    name = "SendBulkActual",
    srcs = ["SendBulkActual.java"],
    deps = [
        "//java/api-client:java_api_lib",
    ],
)

java_binary(
    name = "SendPrediction",
    srcs = ["SendPrediction.java"],
    deps = [
        "//java/api-client:java_api_lib",
    ],
)

java_binary(
    name = "SendBulkPrediction",
    srcs = ["SendBulkPrediction.java"],
    deps = [
        "//java/api-client:java_api_lib",
    ],
)

java_binary(
    name = "SendTrainingRecords",
    srcs = ["SendTrainingRecords.java"],
    deps = [
        "//java/api-client:java_api_lib",
    ],
)

java_binary(
    name = "SendValidationRecords",
    srcs = ["SendValidationRecords.java"],
    deps = [
        "//java/api-client:java_api_lib",
    ],
)
